development: &db
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_DEV_URL"] %>
  variables:
    sql_mode: traditional 

test:
  <<: *db
  url: <%= ENV["DATABASE_TEST_URL"] %>
  variables:
    sql_mode: traditional

production:
  <<: *db
  database: db/production
