name: CI

on:
  pull_request:
    branches: [main]

env:
  RAILS_ENV: test

jobs:
  rspec-unit-feature-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up Database
        run: |
          cp config/database.yml.sample config/database.yml && 
          cp docker-compose.yml.sample docker-compose.yml &&
          cp .env.ci .env
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails db:seed

      - name: Run RSpec Tests
        run: bundle exec rspec
